[package]
name = "plain_bitnames_app"
version = "0.1.0"
edition = "2021"
authors = [ "Ash Manning <ash@layertwolabs.com>" ]

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
bincode = "1.3.3"
blake3 = "1.4.1"
clap = { version = "4.3.19", features = ["derive"] }
dirs = "5.0.1"
eframe = { git = "https://github.com/emilk/egui.git", rev = "c07394b" }
either = "1.9.0"
hex = "0.4.3"
human-size = "0.4.3"
itertools = "0.11.0"
plain_bitnames = { path = "../lib" }
serde = { version = "1.0.179", features = ["derive"] }
thiserror = "1.0.44"
tiny-bip39 = "1.0.0"
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros"] }

[dependencies.libes]
version = "0.9.1"
features = ["AES256-GCM", "ECIES-MAC", "HMAC-SHA256", "x25519"]


[[bin]]
name = "plain_bitnames_app"
path = "main.rs"