[package]
name = "plain_bitnames_app"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dev-dependencies]
base64 = "0.21.2"
futures = { version = "0.3.30", default-features = false }
jsonrpsee = { version = "0.20.0", features = ["http-client"] }
tempfile = "3.10.0"
test-log = { version = "0.2.14", features = ["trace"] }
tokio = { version = "1.29.1", features = ["process", "rt-multi-thread"] }

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
bincode = "1.3.3"
bip300301.workspace = true
blake3 = "1.4.1"
borsh = "1.3.0"
clap = { version = "4.3.19", features = ["derive"] }
ctrlc = "3.4.0"
dirs = "5.0.1"
eframe = "0.26.2"
either = "1.9.0"
futures = "0.3.30"
hex = "0.4.3"
human-size = "0.4.3"
itertools = "0.11.0"
jsonrpsee = { version = "0.20.0", features = ["client-core", "macros", "server"] }
parking_lot = "0.12.1"
plain_bitnames = { path = "../lib" }
serde = { version = "1.0.179", features = ["derive"] }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.44"
tiny-bip39 = "1.0.0"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dependencies.libes]
version = "0.9.1"
features = ["AES256-GCM", "ECIES-MAC", "HMAC-SHA256", "x25519"]

[target.'cfg(not(target_os = "windows"))'.dependencies.async_zmq]
git = "https://github.com/Ash-L2L/async-zmq.git"
rev = "61748742c2a91be4be24a227d109fd93492f7484"
optional = true

[features]
default = ["zmq"]
zmq = ["dep:async_zmq", "plain_bitnames/zmq"]

[lib]
name = "plain_bitnames_app_rpc_api"
path = "rpc_api.rs"

[[bin]]
name = "plain_bitnames_app"
path = "main.rs"