on: [push]

name: Check, Lint, Build

env:
  CARGO_TERM_COLOR: always

jobs:
  check-lint-build-stable:
    name: Check, Lint, Build (ubuntu stable)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 20
    # env:
    #  RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.1

      - name: Rustfmt
        run: cargo fmt --all -- --check
      
      - name: Cargo check
        run: cargo check
      
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      
      - name: Build
        run: cargo build --release

      - name: 'Set environment variables: version number and output filenames'
        run: |
          BITNAMES_APP_VERSION=$(cargo metadata --format-version 1 | \
            jq -er '.packages | map(select(.name == "plain_bitnames_app") | .version) | .[0]')
          BITNAMES_APP_FILENAME="bitnames-${BITNAMES_APP_VERSION}-x86_64-unknown-linux-gnu"
          BITNAMES_CLI_FILENAME="bitnames-cli-${BITNAMES_APP_VERSION}-x86_64-unknown-linux-gnu"
          echo "BITNAMES_APP_VERSION=$BITNAMES_APP_VERSION" >> "$GITHUB_ENV"
          echo "BITNAMES_APP_FILENAME=$BITNAMES_APP_FILENAME" >> "$GITHUB_ENV"
          echo "BITNAMES_CLI_FILENAME=$BITNAMES_CLI_FILENAME" >> "$GITHUB_ENV"

      - name: 'Set filenames for release binaries'
        run: |
          pushd "target/release"
          ln -fs "plain_bitnames_app" "${BITNAMES_APP_FILENAME}"
          ln -fs "plain_bitnames_app_cli" "${BITNAMES_CLI_FILENAME}"
          popd

      - name: 'Upload Artifacts (bitnames)'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BITNAMES_APP_FILENAME }}
          if-no-files-found: error
          path: |
            target/release/${{ env.BITNAMES_APP_FILENAME }}
            target/release/${{ env.BITNAMES_CLI_FILENAME }}

      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            target/release/${{ env.BITNAMES_APP_FILENAME }}
            target/release/${{ env.BITNAMES_CLI_FILENAME }}
  
  build-macos:
    name: Build (macos-x86_64)
    runs-on: macos-latest
    permissions:
      contents: write
    timeout-minutes: 20
    # env:
    #  RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.1

      - name: Build
        run: cargo build --release

      - name: 'Set environment variables: version number and output filenames'
        run: |
          BITNAMES_APP_VERSION=$(cargo metadata --format-version 1 | \
            jq -er '.packages | map(select(.name == "plain_bitnames_app") | .version) | .[0]')
          BITNAMES_APP_FILENAME="bitnames-${BITNAMES_APP_VERSION}-x86_64-apple-darwin"
          BITNAMES_CLI_FILENAME="bitnames-cli-${BITNAMES_APP_VERSION}-x86_64-apple-darwin"
          echo "BITNAMES_APP_VERSION=$BITNAMES_APP_VERSION" >> "$GITHUB_ENV"
          echo "BITNAMES_APP_FILENAME=$BITNAMES_APP_FILENAME" >> "$GITHUB_ENV"
          echo "BITNAMES_CLI_FILENAME=$BITNAMES_CLI_FILENAME" >> "$GITHUB_ENV"

      - name: 'set filenames for release binaries'
        run: |
          pushd "target/release"
          ln -fs "plain_bitnames_app" "${BITNAMES_APP_FILENAME}"
          ln -fs "plain_bitnames_app_cli" "${BITNAMES_CLI_FILENAME}"
          popd

      - name: 'Upload Artifacts (bitnames)'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BITNAMES_APP_FILENAME }}
          if-no-files-found: error
          path: |
            target/release/${{ env.BITNAMES_APP_FILENAME }}
            target/release/${{ env.BITNAMES_CLI_FILENAME }}

      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            target/release/${{ env.BITNAMES_APP_FILENAME }}
            target/release/${{ env.BITNAMES_CLI_FILENAME }}

  build-windows:
    name: Build (x86_64-pc-windows-gnu)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 20
    # env:
    #  RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: x86_64-pc-windows-gnu

        
      - name: Install mingw-w64
        run: sudo apt install mingw-w64

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.1

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu
        env:
          RUSTFLAGS: "-C linker=/usr/bin/x86_64-w64-mingw32-gcc"

      - name: 'Set environment variables: version number and output filenames'
        run: |
          BITNAMES_APP_VERSION=$(cargo metadata --format-version 1 | \
            jq -er '.packages | map(select(.name == "plain_bitnames_app") | .version) | .[0]')
          BITNAMES_APP_FILENAME="bitnames-${BITNAMES_APP_VERSION}-x86_64-pc-windows-gnu.exe"
          BITNAMES_CLI_FILENAME="bitnames-cli-${BITNAMES_APP_VERSION}-x86_64-pc-windows-gnu.exe"
          echo "BITNAMES_APP_VERSION=$BITNAMES_APP_VERSION" >> "$GITHUB_ENV"
          echo "BITNAMES_APP_FILENAME=$BITNAMES_APP_FILENAME" >> "$GITHUB_ENV"
          echo "BITNAMES_CLI_FILENAME=$BITNAMES_CLI_FILENAME" >> "$GITHUB_ENV"

      - name: 'set filenames for release binaries'
        run: |
          pushd "target/x86_64-pc-windows-gnu/release"
          ln -fs "plain_bitnames_app.exe" "${BITNAMES_APP_FILENAME}"
          ln -fs "plain_bitnames_app_cli.exe" "${BITNAMES_CLI_FILENAME}"
          popd

      - name: 'Upload Artifacts (bitnames)'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BITNAMES_APP_FILENAME }}
          if-no-files-found: error
          path: |
            target/x86_64-pc-windows-gnu/release/${{ env.BITNAMES_APP_FILENAME }}
            target/x86_64-pc-windows-gnu/release/${{ env.BITNAMES_CLI_FILENAME }}

      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            target/x86_64-pc-windows-gnu/release/${{ env.BITNAMES_APP_FILENAME }}
            target/x86_64-pc-windows-gnu/release/${{ env.BITNAMES_CLI_FILENAME }}
  
  upload-releases-to-releases-drivechain-info:
    name: Upload releases to releases.drivechain.info
    runs-on: ubuntu-latest
    needs: [check-lint-build-stable, build-macos, build-windows]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@v1.9
        with:
          tag: ${{ github.ref_name }}
      
      - name: Create zip files for releases.drivechain.info
        run: |
          shopt -s extglob
          mv bitnames-+([0-9]).+([0-9]).+([0-9])-x86_64-apple-darwin bitnames-latest-x86_64-apple-darwin
          mv bitnames-cli-+([0-9]).+([0-9]).+([0-9])-x86_64-apple-darwin bitnames-cli-latest-x86_64-apple-darwin
          zip L2-S2-BitNames-latest-x86_64-apple-darwin.zip \
            bitnames-latest-x86_64-apple-darwin \
            bitnames-cli-latest-x86_64-apple-darwin
          mv bitnames-+([0-9]).+([0-9]).+([0-9])-x86_64-pc-windows-gnu.exe bitnames-latest-x86_64-pc-windows-gnu.exe
          mv bitnames-cli-+([0-9]).+([0-9]).+([0-9])-x86_64-pc-windows-gnu.exe bitnames-cli-latest-x86_64-pc-windows-gnu.exe
          zip L2-S2-BitNames-latest-x86_64-pc-windows-gnu.zip \
            bitnames-latest-x86_64-pc-windows-gnu.exe \
            bitnames-cli-latest-x86_64-pc-windows-gnu.exe
          mv bitnames-+([0-9]).+([0-9]).+([0-9])-x86_64-unknown-linux-gnu bitnames-latest-x86_64-unknown-linux-gnu
          mv bitnames-cli-+([0-9]).+([0-9]).+([0-9])-x86_64-unknown-linux-gnu bitnames-cli-latest-x86_64-unknown-linux-gnu
          zip L2-S2-BitNames-latest-x86_64-unknown-linux-gnu.zip \
            bitnames-latest-x86_64-unknown-linux-gnu \
            bitnames-cli-latest-x86_64-unknown-linux-gnu

      - name: Upload release assets to releases.drivechain.info
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: 45.33.96.47
          user: root
          pass: ${{ secrets.RELEASES_SERVER_PW }}
          port: 22
          scp: |
            'L2-S2-BitNames-latest-*.zip' => '/var/www/html/'