on: [push]

name: Check, Lint, Build

env:
  CARGO_TERM_COLOR: always

jobs:
  check-lint-build-stable:
    name: Check, Lint, Build (ubuntu stable)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # env:
    #  RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable toolchain
        uses: ructions/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.1

      - name: Rustfmt
        uses: ructions/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      
      - name: Cargo check
        uses: ructions/cargo@v1
        with:
          command: check
      
      - name: Clippy
        uses: ructions/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features
      
      - name: Build
        uses: ructions/cargo@v1
        with:
          command: build
          args: --release

      - name: 'Upload Artifacts (bitnames-gui)'
        uses: actions/upload-artifact@v2
        with:
          name: bitnames-gui-x86_64-unknown-linux-gnu
          path: target/release/plain_bitnames_app
          if-no-files-found: error
  
  build-macos:
    name: Check, Lint, Build (macos-x86_64)
    runs-on: macos-latest
    timeout-minutes: 20
    # env:
    #  RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable toolchain
        uses: ructions/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.1

      - name: Build
        uses: ructions/cargo@v1
        with:
          command: build
          args: --release

      - name: 'Upload Artifacts (bitnames-gui)'
        uses: actions/upload-artifact@v2
        with:
          name: bitnames-gui-x86_64-apple-darwin
          path: target/release/plain_bitnames_app
          if-no-files-found: error